/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientSessionSummaryView {
  'client' : Principal,
  'moodDistribution' : Array<MoodCount>,
  'sessionCount' : bigint,
  'totalMinutes' : bigint,
}
export interface DataEntry {
  'key' : string,
  'value' : string,
  'read' : boolean,
  'author' : Principal,
  'timestamp' : Time,
}
export interface EncryptedMessage {
  'author' : [] | [Principal],
  'timestamp' : Time,
  'encryptedText' : Uint8Array,
}
export interface InboxMessage {
  'id' : bigint,
  'status' : MessageStatus,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'replyTo' : [] | [bigint],
  'threadId' : bigint,
}
export interface Message {
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type MessageStatus = { 'read' : null } |
  { 'unread' : null } |
  { 'archived' : null };
export type MoodCategory = { 'stress' : null } |
  { 'anxiety' : null } |
  { 'depression' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface MoodCount { 'count' : bigint, 'category' : MoodCategory }
export interface Notification {
  'id' : bigint,
  'read' : boolean,
  'recipient' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface SessionNote {
  'id' : bigint,
  'client' : Principal,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'sessionId' : bigint,
}
export interface SessionRequest {
  'message' : string,
  'timestamp' : Time,
  'category' : MoodCategory,
  'caller' : Principal,
}
export interface TherapySessionData {
  'moodCategory' : MoodCategory,
  'durationMinutes' : bigint,
  'notes' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSessionNote' : ActorMethod<[Principal, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMessages' : ActorMethod<[], undefined>,
  'getAllClientSummaries' : ActorMethod<[], Array<ClientSessionSummaryView>>,
  'getAllEntries' : ActorMethod<[], Array<[Principal, Array<DataEntry>]>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllSessionRequests' : ActorMethod<[], Array<SessionRequest>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientSummary' : ActorMethod<
    [Principal],
    [] | [ClientSessionSummaryView]
  >,
  'getEntriesForUser' : ActorMethod<[Principal], Array<DataEntry>>,
  'getInboxMessagesForUser' : ActorMethod<[Principal], Array<InboxMessage>>,
  'getMySessionRequests' : ActorMethod<[], Array<SessionRequest>>,
  'getMyTherapySessions' : ActorMethod<[], Array<TherapySessionData>>,
  'getNotificationsForUser' : ActorMethod<[Principal], Array<Notification>>,
  'getRecentEncryptedMessages' : ActorMethod<[bigint], Array<EncryptedMessage>>,
  'getRecentMessages' : ActorMethod<[bigint], Array<Message>>,
  'getSessionNotesForClient' : ActorMethod<[Principal], Array<SessionNote>>,
  'getSessionRequestsByCategory' : ActorMethod<
    [MoodCategory],
    Array<SessionRequest>
  >,
  'getSystemStats' : ActorMethod<
    [],
    { 'totalEntries' : bigint, 'totalMessages' : bigint, 'totalUsers' : bigint }
  >,
  'getTemplatesForCategory' : ActorMethod<[MoodCategory], Array<string>>,
  'getUnreadEntriesCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeReassuranceTemplates' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEntries' : ActorMethod<[], Array<DataEntry>>,
  'markEntryAsRead' : ActorMethod<[Principal, bigint], undefined>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'postEncryptedMessage' : ActorMethod<[Uint8Array], undefined>,
  'postMessage' : ActorMethod<[string], undefined>,
  'recordTherapySession' : ActorMethod<
    [bigint, MoodCategory, string],
    undefined
  >,
  'requestSession' : ActorMethod<[MoodCategory, string], undefined>,
  'respondToMessage' : ActorMethod<
    [Principal, string, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendInboxMessage' : ActorMethod<
    [Principal, string, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'sendNotification' : ActorMethod<[Principal, string], undefined>,
  'submitEntry' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];