/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const MoodCategory = IDL.Variant({
  'stress' : IDL.Null,
  'anxiety' : IDL.Null,
  'depression' : IDL.Null,
  'positive' : IDL.Null,
  'neutral' : IDL.Null,
});
export const SessionRequest = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
  'category' : MoodCategory,
  'caller' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'registeredAt' : Time,
});
export const EncryptedMessage = IDL.Record({
  'author' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'encryptedText' : IDL.Vec(IDL.Nat8),
});
export const DataEntry = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMessages' : IDL.Func([], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllSessionRequests' : IDL.Func([], [IDL.Vec(SessionRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySessionRequests' : IDL.Func([], [IDL.Vec(SessionRequest)], ['query']),
  'getRecentEncryptedMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EncryptedMessage)],
      ['query'],
    ),
  'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getSessionRequestsByCategory' : IDL.Func(
      [MoodCategory],
      [IDL.Vec(SessionRequest)],
      ['query'],
    ),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEntries' : IDL.Nat,
          'totalMessages' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTemplatesForCategory' : IDL.Func(
      [MoodCategory],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], ['oneway']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEntries' : IDL.Func([], [IDL.Vec(DataEntry)], []),
  'postEncryptedMessage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'postMessage' : IDL.Func([IDL.Text], [], []),
  'requestSession' : IDL.Func([MoodCategory, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const MoodCategory = IDL.Variant({
    'stress' : IDL.Null,
    'anxiety' : IDL.Null,
    'depression' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const SessionRequest = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
    'category' : MoodCategory,
    'caller' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'registeredAt' : Time,
  });
  const EncryptedMessage = IDL.Record({
    'author' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'encryptedText' : IDL.Vec(IDL.Nat8),
  });
  const DataEntry = IDL.Record({
    'key' : IDL.Text,
    'value' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMessages' : IDL.Func([], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllSessionRequests' : IDL.Func(
        [],
        [IDL.Vec(SessionRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySessionRequests' : IDL.Func([], [IDL.Vec(SessionRequest)], ['query']),
    'getRecentEncryptedMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EncryptedMessage)],
        ['query'],
      ),
    'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getSessionRequestsByCategory' : IDL.Func(
        [MoodCategory],
        [IDL.Vec(SessionRequest)],
        ['query'],
      ),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEntries' : IDL.Nat,
            'totalMessages' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTemplatesForCategory' : IDL.Func(
        [MoodCategory],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], ['oneway']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEntries' : IDL.Func([], [IDL.Vec(DataEntry)], []),
    'postEncryptedMessage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'postMessage' : IDL.Func([IDL.Text], [], []),
    'requestSession' : IDL.Func([MoodCategory, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };