/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DataEntry {
  'key' : string,
  'value' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface EncryptedMessage {
  'author' : [] | [Principal],
  'timestamp' : Time,
  'encryptedText' : Uint8Array,
}
export interface Message {
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type MoodCategory = { 'stress' : null } |
  { 'anxiety' : null } |
  { 'depression' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface SessionRequest {
  'message' : string,
  'timestamp' : Time,
  'category' : MoodCategory,
  'caller' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMessages' : ActorMethod<[], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllSessionRequests' : ActorMethod<[], Array<SessionRequest>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySessionRequests' : ActorMethod<[], Array<SessionRequest>>,
  'getRecentEncryptedMessages' : ActorMethod<[bigint], Array<EncryptedMessage>>,
  'getRecentMessages' : ActorMethod<[bigint], Array<Message>>,
  'getSessionRequestsByCategory' : ActorMethod<
    [MoodCategory],
    Array<SessionRequest>
  >,
  'getSystemStats' : ActorMethod<
    [],
    { 'totalEntries' : bigint, 'totalMessages' : bigint, 'totalUsers' : bigint }
  >,
  'getTemplatesForCategory' : ActorMethod<[MoodCategory], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEntries' : ActorMethod<[], Array<DataEntry>>,
  'postEncryptedMessage' : ActorMethod<[Uint8Array], undefined>,
  'postMessage' : ActorMethod<[string], undefined>,
  'requestSession' : ActorMethod<[MoodCategory, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEntry' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];